on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        default: docker.io
      context:
        required: false
        type: string
        default: .
      image-tags:
        required: false
        type: string
        default: latest
      platforms:
        required: false
        type: string
        default: "linux/amd64,linux/arm64"

jobs:
  buildAndPublishImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: environment
        run: env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ inputs.image-tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm tags
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '(.features[] | select(has("name")) | select(.name == "feature-a")).image = " feature-a:1.1.1"' -i helm/values.yaml

      - name: Check code in and push
        run: |
          git add helm/values.yaml
          git commit -m 'Updated helm/values.yaml file.'
          git push